const mongoose = require("mongoose");

const AnimeSchema = new mongoose.Schema({
    _: {
        id: { type: Number, required: true },
        idMal: { type: Number, required: true },
        title: {
            romaji: { type: String, required: false },
            english: { type: String, required: false },
            native: { type: String, required: false },
            userPreferred: { type: String, required: false },
        },
        format: { type: String, required: true },
        status: { type: String, required: true },
        episodes: { type: Number, required: true },
        description: { type: String, required: true },
        startDate: {
            year: { type: Number, required: false },
            month: { type: Number, required: false },
            day: { type: Number, required: false },
        },
        endDate: {
            year: { type: Number, required: false },
            month: { type: Number, required: false },
            day: { type: Number, required: false },
        },
        season: { type: String, required: true },
        seasonYear: { type: Number, required: false },
        duration: { type: Number, required: false },
        countryOfOrigin: { type: String, required: true },
        isLicensed: { type: Boolean, required: false },
        source: { type: String, required: true },
        hashtag: { type: String, required: true },
        trailer: { type: String, required: true },
        updatedAt: { type: Number, required: false },
        coverImage: {
            large: { type: String, required: false },
            medium: { type: String, required: false },
            small: { type: String, required: false },
            color: { type: String, required: false },
        },
        bannerImage: { type: String, required: false },
        genres: { type: Array, required: false },
        synonyms: { type: Array, required: false },
        averageScore: { type: Number, required: false },
        meanScore: { type: Number, required: false },
        favourites: { type: Number, required: false },
        popularity: { type: Number, required: false },
        trending: { type: Number, required: false },
        tags: { type: Array, required: false },
        relations: { type: Array, required: false },
        characters: { type: Array, required: false },
        staff: { type: Array, required: false },
        studios: { type: Array, required: false },
        isFavourite: { type: Boolean, required: false },
        isAdult: { type: Boolean, required: false },
        isLocked: { type: Boolean, required: false },
        nextAiringEpisode: {
            timeUntilAiring: { type: Number, required: false },
            airingAt: { type: Number, required: false },
            episode: { type: Number, required: false },
        },
        airingSchedule: { type: Array, required: false },
        trends: { type: Array, required: false },
        externalLinks: { type: Array, required: false },
        streamingEpisodes: { type: Array, required: false },
        rankings: { type: Array, required: false },
        mediaListEntry: null,
        reviews: null,
        siteUrl: { type: String, required: true },
        autoCreateForumThread: { type: Boolean, required: false },
        modNotes: null,
        stats: {
            scoreDistribution: { type: Array, required: false },
            statusDistribution: { type: Array, required: false },
        },
        isRecommendationBlocked: { type: Boolean, required: false },
        recommendations: { type: Array, required: false },
    },
    episodes: { type: Array, required: false }
});

const Anime = (module.exports = mongoose.model("Anime", AnimeSchema));
